### ISSUE TITLE
WiFi milestone: implement connecting to unencrypted networks

### ISSUE THREAD

**Issue by stapelberg** [gokrazy/gokrazy#57]
I have recently looked at the WiFi situation again, which has been previously discussed in https://github.com/gokrazy/gokrazy/issues/13.

This issue focuses specifically only on unencrypted networks, because:
* Connecting to unencrypted networks is an achievable milestone, and I have a clear idea of how the design should look like,
* One has to start somewhere, and perhaps people are more motivated to contribute further WiFi improvements after this hurdle is already taken.
* In some scenarios this might be better than having no connectivity at all.
* Once https://github.com/gokrazy/gokrazy/pull/53 (TLS support) is implemented, some people might be okay with running a TLS-secured gokrazy instance on an unencrypted WiFi network. This is comparable to university networks that are unencrypted at the WiFi layer, but require a VPN for connectivity.
  * Alternatively, running wireguard (which is included since Linux 5.6, which gokrazy uses) might be an alternative to secure your communication.

Please keep general WiFi discussion over in https://github.com/gokrazy/gokrazy/issues/13.

Milestones:
* [x] [enable necessary kernel options](https://github.com/gokrazy/kernel/commit/e7d397b3cf443fdce09bc567dd568de4f6b4f1c1)
* [x] [contribute Connect() function to mdlayher/wifi](https://github.com/mdlayher/wifi/pull/25)
* [x] [create wifi daemon repository `github.com/gokrazy/wifi`](https://github.com/gokrazy/wifi)
* [x] [wifi daemon: feed firmware into sysfs](https://github.com/gokrazy/wifi/commit/076ae37526a827ef8ab1abd9b7db956a00415722)
  * We build the brcmfmac module into the kernel (not as a module), meaning it will be loaded before the root file system is available, which is where we store the firmware files. Hence, instead of storing the firmware files in the root file system, we can just bundle them with the wifi daemon and [provide them via the sysfs firmware fallback interface](https://wiki.tizen.org/Usage_and_Mechanism_of_kernel_function_%22request_firmware()%22#Load_firmware_in_userspace).
* [x] [dhcp: make network interface configurable](https://github.com/gokrazy/gokrazy/commit/9e57e3cf2ee659c22a6e6d1e02f0d58bb66098f5)
* [x] [wifi daemon: manage `/gokrazy/dhcp` process for wifi interface while connected](https://github.com/gokrazy/wifi/commit/a495177559c4e5dc4c946c65f43d1ff759326b32)
* [x] once https://github.com/mdlayher/wifi/pull/26 is merged, update go.mod

**Update:** this is now done. I have verified that the Raspberry Pi successfully connects to an unencrypted WiFi network (with a MAC address filter), obtains a DHCPv4 and IPv6 SLAAC address and is able to ping other devices, using the following packer invocation:

```
% gokr-packer -update=yes \
github.com/gokrazy/hello \
github.com/gokrazy/breakglass \
github.com/gokrazy/serial-busybox \
github.com/gokrazy/wifi
```

…and the following `go.mod` file (so that you can reproduce my invocation if you’d like):
```
module gokrazy/hello

require (
	github.com/gokrazy/breakglass v0.0.0-20190207134123-d3f89caa0ac9 // indirect
	github.com/gokrazy/firmware v0.0.0-20200523135844-00ba8f4807f9 // indirect
	github.com/gokrazy/gokrazy v0.0.0-20200527062450-9e57e3cf2ee6 // indirect
	github.com/gokrazy/hello v0.0.0-20170304101055-fa4e42473124 // indirect
	github.com/gokrazy/kernel v0.0.0-20200526220649-e7d397b3cf44 // indirect
	github.com/gokrazy/serial-busybox v0.0.0-20200521210859-b4f0c5c3f3aa // indirect
	github.com/gokrazy/wifi v0.0.0-20200527114125-c278286ee603 // indirect
	github.com/google/shlex v0.0.0-20181106134648-c34317bd91bf // indirect
	github.com/kr/pty v1.1.8 // indirect
)
```

…and the following configuration:
```
% sudo mount /dev/sdx4 /mnt
% echo '{"ssid": "I/O Tee"}' | sudo tee /mnt/wifi.json
% sudo umount /mnt
```

This is what the gokrazy web interface shows:

![2020-05-27-gokrazy-wifi-unencrypted](https://user-images.githubusercontent.com/55506/83043715-800fe600-a043-11ea-8ff0-61218b70276e.jpg)

And this is how I configured my TP-Link TL-WDR4300 WiFi router for testing:

![iotee](https://user-images.githubusercontent.com/55506/83043786-95851000-a043-11ea-9ef0-b11e823d17bb.jpg)
